Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('curso.urls', namespace="curso")),
    path('courses', include('curso.urls'))

]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curso/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, Courses, DetailCourses, Pesquisa, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view

app_name = 'curso'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('courses', Courses.as_view(), name='courses'),
    path('courses/<int:pk>', DetailCourses.as_view(), name='DetailCourses'),
    path('pesquisa/', Pesquisa.as_view(), name='PesquisaCurso'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/' , auth_view.PasswordChangeView.as_view(template_name='editarperfil.html' ,
                                                              success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]



curso/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
LISTA_CATEGORIA = (
    ("PRGRAMACAO", "Programação"),
    ("DJANGO", "Django"),
    ("ingles", "Ingles"),
    ("desenho", "Desenho")
)

# Create your models here.


#criar o curso
class Curso(models.Model):
    thumb = models.ImageField(upload_to="Thumb_Cursos")
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    category = models.CharField(max_length=15, choices=LISTA_CATEGORIA)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title
#criar os episodios

class Episodio(models.Model):
    course = models.ForeignKey("Curso", related_name="episodios", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo

class Usuario(AbstractUser):
    cursos_vistos = models.ManyToManyField("Curso")


curso/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

curso/views.py
from django.shortcuts import render, redirect, reverse
from .models import Curso, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
#def homepage(request):
#    return render(request, "homepage.html")

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage


    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('curso:courses')
        else:
            return super().get(request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('curso:login')
        else:
            return reverse('curso:criarconta')

#def courses(request):
    #context = {}
    #lista_cursos = Curso.objects.all()
    #context['lista_cursos'] = lista_cursos
    #return render(request, "courses.html", context)

class Courses(LoginRequiredMixin, ListView):
    template_name = "courses.html"
    model = Curso

class DetailCourses(LoginRequiredMixin, DetailView):
    template_name = "DetailCourses.html"
    model = Curso

    def get(self, request, *args, **kwargs):
        curso = self.get_object()
        curso.visualizacoes += 1
        curso.save()
        usuario = request.user
        usuario.cursos_vistos.add(curso)
        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(DetailCourses, self).get_context_data(**kwargs)
        cursos_relacionados = Curso.objects.filter(category=self.get_object().category)[0:5]
        context["cursos_relacionados"] = cursos_relacionados
        return context

class Pesquisa(ListView):
    template_name = "PesquisaCurso.html"
    model = Curso

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = Curso.objects.filter(title__icontains=termo_pesquisa)
            return object_list
        else:
            return None

class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('curso:courses')


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('curso:login')

curso/templates/DetailCourses.html
{% extends 'courses.html' %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}


{% block content %}
   <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-black my-4">
                    {{ object.title }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-black my-4">
                    {{ object.description }}
                </p>
                <div class="flex my-4">
                    <a href="{{ object.episodios.first.video }}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-black-200 text-3xl font-medium">
                    Descrição
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-black-100 text-lg">
                        {{ object.description }}
                    </p>
                </div>

                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="text-black-200 text-3xl font-medium">
                        Episódios

                    </h2>
                    {% for episodio in object.episodios.all %}
                        <h3 class='text-lg'>
                            <a href="{{ episodio.video }}">
                                <p>Episódio {{ forloop.counter }}: {{ episodio.title }}</p>
                            </a>
                        </h3>
                    {% endfor %}
                </div>

            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-black-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for cursos in cursos_relacionados  %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'curso:DetailCourses' cursos.pk %}">
                                <img src="{{ cursos.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>








{% endblock %}

curso/templates/PesquisaCurso.html
{% extends 'base.html' %}


{% block titulo %}

Pesquisa de Cursos

{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for cursos in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'curso:DetailCourses' cursos.pk %}">
                          <img src="{{ cursos.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>

{% endblock %}

curso/templates/courses.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block titulo %}
    {% endblock %}
  </title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
   <script src="https://cdn.tailwindcss.com"></script>
  <style>
$itemGrow: 1.2;
$duration: 250ms;

html {
 scroll-behavior: smooth;
}

body {
 margin: 0;
 background-color: #000;
}

h1 {
 font-family: Arial;
 color: red;
 text-align: center;
}

.wrapper {
 display: grid;
 grid-template-columns: repeat(3,100%);
 overflow:hidden;
 scroll-behavior: smooth;

 section {
  width: 100%;
  position: relative;
  display: grid;
  grid-template-columns: repeat(5, auto);
  margin: 20px 0;

  .item {
   padding: 0 2px;
   transition: $duration all;

   &:hover {
    margin: 0 40px;
    transform: scale(1.2);
   }

  }

  a {
   position: absolute;
   color: #fff;
   text-decoration: none;
   font-size: 6em;
   background:rgb(0,0,0);
   width: 80px;
   padding: 20px;
   text-align: center;
   z-index: 1;

   &:nth-of-type(1) {
    top:0; bottom:0; left:0;
    background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
   }
   &:nth-of-type(2) {
    top:0; bottom:0; right: 0;
    background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
   }

  }

 }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
 a.arrow__btn {
  display:none;
 }
}
  </style>
</head>
<body>
  {% load static %}
  {% include 'navbar.html' %}
  {% block content %}

  <script>
     const nav = document.querySelector('nav')

    document.addEventListener("scroll",e=>{

      if(scrollY>100){
        if(scrollY>window.innerHeight){
        nav.classList.add('invisible')
      }else{
        nav.classList.add('bg-gray-900')
        nav.classList.remove('invisible')
      }
      }else{
        nav.classList.remove('bg-gray-900')
        nav.classList.remove('invisible')
      }
    })
  </script>
   <main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ curso_destaque.thumb. }}');">
      <div>
        <h2 class="text-6xl font-semibold text-white my-4">
          {{ curso_destaque.title }}
        </h2>
        <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
          {{ curso_destaque.description }}
        </p>
        <div class="flex my-4">

            <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
              <ion-icon name="play" class="text-2xl"></ion-icon>
              <span class="ml-3 font-medium " >
                Play
              </span>
            </button>
          </a>
        </div>
      </div>
    </section>


    <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
        <h2 class="text-gray-200 text-2xl font-medium">
          Novo
        </h2>
        <div class="wrapper">
         <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
          <a href="#section2" class="arrow__btn text-6xl page">‹</a>
           {% for cursos in lista_cursos_recentes %}
           {% if forloop.counter < 5 %}
           <div class="item h-64 w-1/4 m-4">
             <a href="{% url 'curso:DetailCourses' cursos.pk %}">
              <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
             </a>
           </div>
           {% endif %}
           {% endfor %}
            <a href="#section2" class="arrow__btn text-6xl">›</a>
         </section>
          {% if lista_cursos_recentes|length > 4 %}
           <section id="section2" class="flex flex-nowrap items-center justify-center">
            <a href="#section1" class="arrow__btn text-6xl">‹</a>
             {% for cursos in lista_cursos_recentes %}
             {% if forloop.counter > 4 %}
             <div class="item h-64 w-1/4 m-4">
               <a href="{% url 'cursos:DetailCourses' curso.pk %}">
                <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
               </a>
             </div>
             {% endif %}
             {% endfor %}
            <a href="#section1" class="arrow__btn text-6xl">›</a>
           </section>
          {% endif %}
        </div>
      </div>
    </section>

       <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
        <h2 class="text-gray-200 text-2xl font-medium">
          Em Alta
        </h2>
        <div class="wrapper">
         <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
          <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
           {% for cursos in lista_cursos_emalta %}
           {% if forloop.counter < 5 %}
           <div class="item h-64 w-1/4 m-4">
             <a href="{% url 'curso:DetailCourses' cursos.pk %}">
              <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
             </a>
           </div>
           {% endif %}
           {% endfor %}
            <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
         </section>
          {% if lista_cursos_emalta|length > 4 %}
           <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
            <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
             {% for cursos in lista_cursos_emalta %}
             {% if forloop.counter > 4 %}
             <div class="item h-64 w-1/4 m-4">
               <a href="{% url 'cursos:DetailCourses' curso.pk %}">
                <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
               </a>
             </div>
             {% endif %}
             {% endfor %}
            <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
           </section>
          {% endif %}
        </div>
      </div>
    </section>


       <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
        <h2 class="text-gray-200 text-2xl font-medium">
         Continuar Assistindo
        </h2>
        <div class="wrapper">
         <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
          <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
           {% for cursos in request.user.cursos_vistos.all %}
           {% if forloop.counter < 5 %}
           <div class="item h-64 w-1/4 m-4">
             <a href="{% url 'curso:DetailCourses' cursos.pk %}">
              <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
             </a>
           </div>
           {% endif %}
           {% endfor %}
            <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
         </section>
          {% if request.user.cursos_vistos.all|length > 4 %}
           <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
            <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
             {% for cursos in request.user.cursos_vistos.all %}
             {% if forloop.counter > 4 %}
             <div class="item h-64 w-1/4 m-4">
               <a href="{% url 'cursos:DetailCourses' curso.pk %}">
                <img src="{{ cursos.thumb.url }}" class="rounded-md w-full h-full object-cover">
               </a>
             </div>
             {% endif %}
             {% endfor %}
            <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
           </section>
          {% endif %}
        </div>
      </div>
    </section>

  </main>
  {% endblock %}
<!-- This example requires Tailwind CSS v3.0+ -->
<div class="isolate bg-black">
 <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
  <svg class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678" fill="none" xmlns="http://www.w3.org/2000/svg">
   <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
   <defs>
    <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
     <stop stop-color="#9089FC"></stop>
     <stop offset="1" stop-color="#FF80B5"></stop>
    </linearGradient>
   </defs>
  </svg>
 </div>
 <div class="px-6 pt-6 lg:px-8">
  <div>
   <nav class="flex h-9 items-center justify-between" aria-label="Global">
    <div class="flex lg:min-w-0 lg:flex-1" aria-label="Global">
     <a href="#" class="-m-1.5 p-1.5">
      <span class="sr-only">Your Company</span>
      <img class="h-8" src="" alt="">
     </a>
    </div>
    <div class="flex lg:hidden">
     <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
      <span class="sr-only">Open main menu</span>
      <!-- Heroicon name: outline/bars-3 -->
      <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
       <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>
     </button>
    </div>
    <div class="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">

    </div>
   </nav>
   <!-- Mobile menu, show/hide based on menu open state. -->
   <div role="dialog" aria-modal="true">
    <div focus="true" class="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
     <div class="flex h-9 items-center justify-between">
      <div class="flex">
       <a href="#" class="-m-1.5 p-1.5">
        <span class="sr-only">Your Company</span>
        <img class="h-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
       </a>
      </div>
      <div class="flex">
       <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Close menu</span>
        <!-- Heroicon name: outline/x-mark -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
         <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
       </button>
      </div>
     </div>
     <div class="mt-6 flow-root">
      <div class="-my-6 divide-y divide-gray-500/10">
       <div class="space-y-2 py-6">
        <a href="/" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Home</a>

        <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Support</a>

        <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10">Company</a>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>

curso/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-20 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-600 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>Pedro Leite</li>
        </ul>
    </footer>

{% endblock %}

curso/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                  {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'curso:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>Pedro Leite </li>
        </ul>
    </footer>



{% endblock %}

curso/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomePage Cursinho
{% endblock %}

{% block head %}
<style>
    #id_email{
    width: 100%;
    color: #000000;
    padding: 5px 5px;
    }
</style>
{% endblock %}


{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat">
        <div class="z-10 h-full py-32 md:py-0 text-black-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl text-gray-100 md:text-5xl w-10/12 md:w-3/4 text-center">
                Todos os cursos que você possa imaginar em um só lugar
            </h1>
            <h3 class="text-xl text-gray-100 md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm text-gray-100 md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </header>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
           <img class="w-2/12" src="{% static 'images/hashflix.png' %}">
        </a>
    </div>

    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'curso:PesquisaCurso' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        <div class="mr-2">
            {% if user.is_authenticated %}
            <a href="{% url 'curso:logout' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Sair
                </button>
            </a>
            {% else %}
            <a href="{% url 'curso:login' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'curso:editarperfil' user.pk %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>

</nav>